config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {sessions: 'members/sessions', registrations: 'members/registrations'}

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base

  #status
  enum status: [:active, :processing, :sold]

  #searchkick gem
  searchkick

  #constantes
  QTT_PER_PAGE = 6

  #ratyrate gem
  ratyrate_rateable 'quality'

  #callbacks
  before_save :md_to_html

  #associations
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  #validates
  validates :title, :description_md, :description_short, :category, :picture, :finish_date, presence: true
  validates :price, numericality: {greater_than: 0}

  #scopes
  scope :descending_order, ->(page) { order(created_at: :desc).page(page).per(QTT_PER_PAGE) }
  scope :to_the, ->(member) { where(member: member) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(QTT_PER_PAGE) }
  #scope :search, ->(q, page) { where("lower(title) LIKE ?", "%#{q.downcase}%").page(page).per(QTT_PER_PAGE) }
  scope :random, ->(quantity) {
    if Rails.env.production?
      limit(quantity).order("RAND()") #MySQL
    else
      limit(quantity).order("RANDOM()") #SQLite
    end
  }

  #paperclip
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #gem MoneyRails
  monetize :price_cents

  def second
    self[1]
  end

  def third
    self[2]
  end

  private

    def md_to_html
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)
    end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  #ROLES = {:full_access => 0, :restricted_access => 1}

  #enums
  #enum role: ROLES

  #scope :with_full_access, -> { where(role: ROLES[:full_access])}
  scope :with_restricted_access, -> { with_role(Role.availables[1]) }
  # def self.with_full_access
  #   where(role: 'full_access')
  # end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def checked_roles
    self.roles.collect do |role|
      role.name
    end
  end

  def roles_descriptions
    self.roles.collect do |role|
      Role::OPTIONS[role.name.to_sym]
    end
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base

  #gem friendly id
  include FriendlyId
  friendly_id :description, use: :slugged

  # associations
  has_many :ads

  #validations
  validates_presence_of :description

  #scopes
  scope :order_by_description, -> { order(:description) }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ActiveRecord::Base

  #ratyrate gem
  ratyrate_rater

  #associations
  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  #validations
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "É necessário preencher os campos Primeiro e Segundo nome.")
    end
  end

  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  #status
  enum status: [:requested, :waiting, :analysing, :paid,
                :avaliable, :dispute, :returned, :canceled, :debited,
                :temporary_retention]

  #associations
  belongs_to :ad
  belongs_to :buyer, class_name: "Member"
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base
  belongs_to :member

  def full_name
    "#{self.first_name} #{self.second_name}"
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  OPTIONS = {
    full_access: "Acesso Completo",
    restricted_access: "Acesso Restrito"
  }

  def self.availables
    OPTIONS.map do |key, value|
      key.to_s
    end

  end
  has_and_belongs_to_many :admins, :join_table => :admins_roles

  belongs_to :resource,
             :polymorphic => true #Rails 5>+, :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  validates :name, inclusion: {in: Role.availables}

  scopify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  #pundit
  include Pundit

  #manages errors pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #layout
  layout :layout_by_resouce

  protected

    def layout_by_resouce
      if devise_controller? && resource_name == :admin
        "backoffice_devise"

      elsif devise_controller? && resource_name == :member
        "site_devise"
      else
        "application"
      end
    end

    def user_not_authorized
      flash[:alert] = "Você não está autorizado a executar essa ação"
      redirect_to(request.referrer || root_path)
    end

  private
    def store_current_location
      store_location_for(:member, request.url)
    end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"


  def pundit_user
    current_admin #current_user for admin
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"

end

app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end

  def devise_sign_in?
    params[:controller] == 'members/sessions' ? '' : 'display:none;'
  end


  def devise_sign_up?
    params[:controller] == 'members/registrations' ? '' : 'display:none;'
  end
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
  <h1 class="page-header"> Admnistradores </h1>

  <% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
          <% @admin.errors.full_messages.each do |message|%>
            <li><%= message %></li>
          <%end%>
        </ul>
    </div>
  <%end%>

  <div class="panel panel-default">
          <div class="panel-heading">
              <%= action %>
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">

            <div class="col-lg-6">
              <%= form_for([:backoffice, @admin]) do |f|%>
                <div class="form-group">
                    <%= f.label :name%>
                    <%= f.text_field :name, class: "form-control", placeholder: "Nome do Adminstrador"%>
                </div>
                <div class="form-group">
                    <%= f.label :email%>
                    <%= f.email_field :email, class: "form-control", placeholder: "Email do Adminstrador"%>
                </div>
                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role%>
                        <%= f.collection_check_boxes(:role_ids, options_for_roles, :id, :description, checked: @admin.checked_roles) do |b| %>
                            <div class="radio">
                                <label>
                                    <%= b.label {b.check_box + b.text} %>
                                </label>
                            </div>
                        <%end%>
                    </div>
                <%end%>

                <div class="form-group">
                    <%= f.label :password%>
                    <%= f.password_field :password, class: "form-control", autocomplete: "off", placeholder: "Senha"%>
                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation%>
                    <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off", placeholder: "Confirmação de Senha"%>
                </div>
                <button type="submit" class="btn btn-default">Salvar</button>
              <%end%>
            </div>

          </div>
          <!-- /.panel-body -->
  </div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Nova mensagem</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do%>

            <div class="form-group">
              <label for="recipient-text" class="control-label">Para:</label>
              <%= text_field_tag(:'recipient-text', nil, class:"form-control", readonly: "readonly") %>
            </div>

            <div class="form-group">
              <label for="recipient-name" class="control-label">Assunto:</label>
              <%= text_field_tag(:'subject-text', nil, class:"form-control", autocomplete: :off, required: "required") %>
            </div>

            <div class="form-group">
              <label for="message-text" class="control-label">Menssagem:</label>
              <%= text_area_tag(:'message-text', nil, class:"form-control", required: "required") %>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
              <%= submit_tag "Enviar", class: "btn btn-primary" %>
            </div>

        <%end%>
      </div>

    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <%= javascript_tag "$.notify( { message: '#{notice}'}, { type: 'success', placement: {
    from: 'top', align: 'center' }});" %>
<%end%>

<% if alert %>
  <%= javascript_tag "$.notify( { message: '#{alert}'}, { type: 'danger', placement: {
    from: 'top', align: 'center' }});" %>
<%end%>